### ISSUE TITLE
Question about the VFHQ dataset

### ISSUE THREAD

**Issue by Hao-tianWang** [Zejun-Yang/AniPortrait#10]
Fantastic work! I have a question about the dataset. Which version of VFHQ dataset did you use, the raw training set w/o resize or the resized 512*512 version? Thanks.

**Comment by Zejun-Yang** [comment]
Thank you for your interest! We use the version  w/o resize.

**Comment by skywalker00001** [comment]
Hello, is there a fast way to download VFHQ dataset? 百度网盘 is too slow~~~
