### ISSUE TITLE
拿例子的源视频和参考图像，跑出来之后就是不张嘴，请问应该怎么排查？

### ISSUE THREAD

**Issue by maple19781016** [Zejun-Yang/AniPortrait#101]
![微信图片_20240408180908](https://github.com/Zejun-Yang/AniPortrait/assets/108562507/cc679ca8-f9e1-443a-a5fe-56b949358d61)

https://github.com/Zejun-Yang/AniPortrait/assets/108562507/c670ead4-e1e4-4c22-a334-c60ab518d9b6

**Comment by Zejun-Yang** [comment]
貌似该视频貌似是用社区整合的ComfyUI流程跑的，所以我们也无法具体定位。您可以尝试我们提供的测试视频configs/inference/video/Aragaki_song.mp4，判断是代码有问题还是您原来使用的源视频张嘴不明显。

**Comment by maple19781016** [comment]
> 貌似该视频貌似是用社区整合的ComfyUI流程跑的，所以我们也无法具体定位。您可以尝试我们提供的测试视频configs/inference/video/Aragaki_song.mp4，判断是代码有问题还是您原来使用的源视频张嘴不明显。另外，背景音乐声音过大也会导致口型推理异常。

好的，谢谢，我跑一下然后再反馈。用的comfyUI是腾讯云上的高性能应用服务器，源视频是从b站截屏成正方形的。

**Comment by maple19781016** [comment]
> 貌似该视频貌似是用社区整合的ComfyUI流程跑的，所以我们也无法具体定位。您可以尝试我们提供的测试视频configs/inference/video/Aragaki_song.mp4，判断是代码有问题还是您原来使用的源视频张嘴不明显。另外，背景音乐声音过大也会导致口型推理异常。

用这个例子视频就可以，我自己找的视频就都不行，不知道为什么，能了解一下视频有什么要求吗？附上1个我找的源视频。

https://github.com/Zejun-Yang/AniPortrait/assets/108562507/dfcade07-f393-4d09-982f-6e9f5946b02d

**Comment by onedotone-wei** [comment]
> > 貌似该视频貌似是用社区整合的ComfyUI流程跑的，所以我们也无法具体定位。您可以尝试我们提供的测试视频configs/inference/video/Aragaki_song.mp4，判断是代码有问题还是您原来使用的源视频张嘴不明显。另外，背景音乐声音过大也会导致口型推理异常。
> 
> 用这个例子视频就可以，我自己找的视频就都不行，不知道为什么，能了解一下视频有什么要求吗？附上1个我找的源视频。
> 
>  f.mp4

同问
另外，还有那个手势，输入图像中的手部已截掉，而且图像中的人像也控制在肩部以上，结果还是会有，但用例子中的图片就不会，这个怎么排查？

**Comment by maple19781016** [comment]
> > > 貌似该视频貌似是用社区整合的ComfyUI流程跑的，所以我们也无法具体定位。您可以尝试我们提供的测试视频configs/inference/video/Aragaki_song.mp4，判断是代码有问题还是您原来使用的源视频张嘴不明显。另外，背景音乐声音过大也会导致口型推理异常。
> > 
> > 
> > 用这个例子视频就可以，我自己找的视频就都不行，不知道为什么，能了解一下视频有什么要求吗？附上1个我找的源视频。
> > f.mp4
> 
> 同问 另外，还有那个手势，输入图像中的手部已截掉，而且图像中的人像也控制在肩部以上，结果还是会有，但用例子中的图片就不会，这个怎么排查？

对，我也是这样，手部还是会乱舞，自己找的几个视频都是这样。不清楚源视频的要求。

**Comment by Zejun-Yang** [comment]
https://github.com/Zejun-Yang/AniPortrait/assets/21038147/3d56565e-7a92-4014-9d22-3fa8b870d734

使用vid2vid.py脚本处理没有异常。
随机出现手部的问题，使用我们最新的代码可以缓解，并且可以尝试更换不同的seed生成视频。
