### ISSUE TITLE
Is there a way to keep the unprocessed data?

### ISSUE THREAD

**Issue by G-force78** [Zejun-Yang/AniPortrait#106]
The data that is generated before the video is made? Such as the individual frames and face landmark frames?

**Comment by Zejun-Yang** [comment]
As for video original frames, you can use ffmpeg to convert the video to images. As for pose landmark images, you can save pose_image_np here (https://github.com/Zejun-Yang/AniPortrait/blob/90f1b67554135b5afcb922b1f3d6d23ecd8f06da/scripts/vid2vid.py#L203).
