### ISSUE TITLE
Gradio demo crops/zooms in on face

### ISSUE THREAD

**Issue by mitchellfox** [Zejun-Yang/AniPortrait#111]
Regarding the latest commit which includes a gradio demo, when using vid2vid I noticed that with the gradio demo it is cropping/zooming in on the face in the output, it also modifies the source photo to be cropped/zoomed in on the face. Whereas, in huggingface demo the output retained the body from the source image and scaled instead of cropping. 

Is there a parameter or config where this can be switched back to scaling instead of cropping?

Thanks for your amazing work!

**Comment by G-force78** [comment]
I think it could be something to do with this

164 # pose_tensor_list = []

    # pose_transform = transforms.Compose(
    #     [transforms.Resize((height, width)), transforms.ToTensor()]
  168  # )

# pose_image_pil = Image.fromarray(cv2.cvtColor(pose_image_np, cv2.COLOR_BGR2RGB))
        # pose_tensor_list.append(pose_transform(pose_image_pil))


pose_transform = transforms.Compose(
        [transforms.Resize((height, width)), transforms.ToTensor()]
    )

**Comment by G-force78** [comment]
It doesnt crop it if the ref image is close to the dimensions of the ref video

https://github.com/Zejun-Yang/AniPortrait/assets/114336644/d9220971-7cbb-4059-b30c-176cab05ae17

![sdgirlcropped512](https://github.com/Zejun-Yang/AniPortrait/assets/114336644/18ea9628-72b8-4e0d-a94c-dd961fcaf0a5)

but will seemingly go too far when it isnt


https://github.com/Zejun-Yang/AniPortrait/assets/114336644/463e6e20-7af9-48b0-b869-464a83523fcd

![sdgirl512](https://github.com/Zejun-Yang/AniPortrait/assets/114336644/de4a7eae-2ab5-49fd-b174-b2c1b87a1ffe)

**Comment by G-force78** [comment]
when I changed expand in crop_single to 1.1 it resulted in this, even more zoomed in


https://github.com/Zejun-Yang/AniPortrait/assets/114336644/45c52bb6-9aff-44e9-827b-a6764b856c0e

**Comment by Zejun-Yang** [comment]
Our purpose in cropping the image is to ensure that the face occupies a larger proportion in the image. You can delete this line of code to disable cropping.

https://github.com/Zejun-Yang/AniPortrait/blob/90f1b67554135b5afcb922b1f3d6d23ecd8f06da/scripts/app.py#L263
