### ISSUE TITLE
about a2m training

### ISSUE THREAD

**Issue by 0913ktg** [Zejun-Yang/AniPortrait#114]
Hello,

I'm reaching out again regarding the training of the audio2mesh model, following up on my previous question in issue #102 . I've developed a custom dataset of approximately 2 hours of facial video data (in MP4 format) and understand the concept of using wav2vec 2.0 960h with two added linear layers for training the A2M model.

However, I need a detailed explanation on how to utilize the extracted audio and frame-by-frame images, i.e., 3D landmarks (lmk_3d), for training.

Should I slice the audio extracted from the video into pieces corresponding to the number of extracted lmk_3d frames, then train the model by mapping each audio slice to its respective lmk_3d on a 1:1 basis?

Or should I use the entire audio from the video with the wav2vec 2.0 960h model, and use its features to generate multiple lmk_3d instances?

Additionally, during training, do I freeze the parameters of wav2vec 2.0 960h and only update the parameters of the two linear layers, or are all parameters updated?

I look forward to your response.
Thank you.

**Comment by FacePoluke** [comment]
You can randomly slice the length of the audio and take a lmk_3d sequence of corresponding length as a training pair. In our training, the feature_extractor of wav2vec is fixed and other components are trained.
