### ISSUE TITLE
如何只输出最终视频，而不是输出3列的视频？

### ISSUE THREAD

**Issue by jayliaoo** [Zejun-Yang/AniPortrait#116]
RT

**Comment by Zejun-Yang** [comment]
#48 
注释掉这一行代码
https://github.com/Zejun-Yang/AniPortrait/blob/415eb04cb246294c141c0de7032767359e64269b/scripts/audio2vid.py#L210

**Comment by jayliaoo** [comment]
> #48 注释掉这一行代码
> 
> https://github.com/Zejun-Yang/AniPortrait/blob/415eb04cb246294c141c0de7032767359e64269b/scripts/audio2vid.py#L210

thx
