### ISSUE TITLE
scripts.app合成的視頻長度

### ISSUE THREAD

**Issue by ioritree** [Zejun-Yang/AniPortrait#119]
L從預設的"60"設置成"0" ,合成後的時間長只有原始視頻的時間一半左右

**Comment by Zejun-Yang** [comment]
可能是输入视频中间某一帧检测人脸失败导致截断。

**Comment by ioritree** [comment]
> 可能是输入视频中间某一帧检测人脸失败导致截断。
之前直接用cmd命令的方式合成沒這問題(同張圖同個視頻)
