### ISSUE TITLE
 no file named config.json and xFormers can't load C++/CUDA extensions

### ISSUE THREAD

**Issue by jsoncode** [Zejun-Yang/AniPortrait#12]
1. Download and configure the model strictly according to the instructions in the readme.
2. ```pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121```

Device and system information：

System: Windows 11
GPU: RTX 4090 24Gb

```
nvidia-smi
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 551.76                 Driver Version: 551.76         CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
```

Error Message: 

```
python -m scripts.pose2vid --config ./configs/prompts/animation.yaml -W 512 -H 512 -L 64
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.1+cu118 with CUDA 1108 (you have 2.2.2+cu121)
    Python  3.10.11 (you have 3.10.6)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
D:\Program Files\Python316\lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
Traceback (most recent call last):
  File "D:\Program Files\Python316\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Program Files\Python316\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\code\open\AniPortrait\scripts\pose2vid.py", line 199, in <module>
    main()
  File "D:\code\open\AniPortrait\scripts\pose2vid.py", line 60, in main
    reference_unet = UNet2DConditionModel.from_pretrained(
  File "D:\Program Files\Python316\lib\site-packages\diffusers\models\modeling_utils.py", line 712, in from_pretrained
    config, unused_kwargs, commit_hash = cls.load_config(
  File "D:\Program Files\Python316\lib\site-packages\diffusers\configuration_utils.py", line 365, in load_config
    raise EnvironmentError(
OSError: Error no file named config.json found in directory ./pretrained_model/stable-diffusion-v1-5.
```

**Comment by G-force78** [comment]
Just download the config file from the sd 1.5 repo in huggingface or copy it.

**Comment by jsoncode** [comment]
Someone has already mentioned this issue before:
https://github.com/Zejun-Yang/AniPortrait/issues/2

Unable to find ./pretrained_model/stable-diffusion-v1-5/config.json

The explanation given is:
> While downloading the config files from HugginFace it prepend the config file names with folder name.
Renamed the same and it worked.

However, there is no file similar to config.json in the root directory of the stable-diffusion-v1-5 project: there is neither xxx_config.json, nor config_xxx.json nor xxx_config_xxx.json
![WX20240328-093913@2x](https://github.com/Zejun-Yang/AniPortrait/assets/13176273/a13c9698-001c-4dfb-8caf-c1ae267b24d0)

And there is only one file model_index.json in the stable-diffusion-v1-5 root directory, so is model_index.json the config.json in the`AniPortrait` project?

**Comment by jsoncode** [comment]
I found a solution like this, but I can't verify it's correct:

https://huggingface.co/CompVis/stable-diffusion-v1-4/discussions/177

**Comment by Zejun-Yang** [comment]
#2 has the same situation.

Actually, the config.json file we need is under ./pretrained_weights/stable-diffusion-v1-5/unet when you download stable-diffusion-v1-5 from hugging face. And we set subfolder="unet" while creating reference unet and denoising unet (see in https://github.com/Zejun-Yang/AniPortrait/blob/bfa15742af3233c297c72b8bb5d7637c5ef5984a/scripts/pose2vid.py#L62). 

Maybe you get the wrong version of diffusers. Make sure diffusers==0.24.0.

**Comment by jsoncode** [comment]
![WechatIMG57](https://github.com/Zejun-Yang/AniPortrait/assets/13176273/beb0973b-9450-4648-9e09-fdaf147fd48f)

I can confirm that the version of my diffusers is 0.24.0
