### ISSUE TITLE
About inflated groupnorm usage. 

### ISSUE THREAD

**Issue by chenerg** [Zejun-Yang/AniPortrait#121]
In the first training stage, no `inflated groupnorm` is used, but in the second training stage you set `use_inflated_groupnorm = true`. Why use two different settings? Should I set `use_inflated_groupnorm = true` during training stage1? Also, can you give me any clue to learn more about the `inflated groupnorm`?

**Comment by Zejun-Yang** [comment]
https://github.com/Zejun-Yang/AniPortrait/blob/8b435af2aeb20c4aef1d2ab746bff64bfe70fe18/src/models/resnet.py#L21

According to this function, it rearranges the batch dimension and frame dimension before applying group normalization. However, in stage 1, the frame dimension is consistently equal to 1. It would be not necessary to do inflated group norm here.
