### ISSUE TITLE
When will the audio2pose be released?

### ISSUE THREAD

**Issue by wubowen416** [Zejun-Yang/AniPortrait#123]
Thank you for your contribution. The generation results are really amazing.

I want to use your audio2pose module for my avatar recent days.
Could you kindly inform that how long will it take for you to release the code?

If more time is absolute necessary, I will try to train my own model, since the details are contained in your paper and it seems quite easy to reproduce.

Thanks in advance.

**Comment by Zejun-Yang** [comment]
Sorry for the delay. The audio2pose model and related code have been released.
