### ISSUE TITLE
OSError: Error no file named config.json found in directory ./pretrained_model/stable-diffusion-v1-5.

### ISSUE THREAD

**Issue by cangyingzhijia** [Zejun-Yang/AniPortrait#124]
root@autodl-container-a1fc46a083-dcb47c0f:~/AniPortrait# python -m scripts.app
Some weights of the model checkpoint at ./pretrained_model/wav2vec2-base-960h were not used when initializing Wav2Vec2Model: ['lm_head.weight', 'lm_head.bias']
- This IS expected if you are initializing Wav2Vec2Model from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing Wav2Vec2Model from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of Wav2Vec2Model were not initialized from the model checkpoint at ./pretrained_model/wav2vec2-base-960h and are newly initialized: ['wav2vec2.masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/AniPortrait/scripts/app.py", line 51, in <module>
    reference_unet = UNet2DConditionModel.from_pretrained(
  File "/root/miniconda3/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 712, in from_pretrained
    config, unused_kwargs, commit_hash = cls.load_config(
  File "/root/miniconda3/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 365, in load_config
    raise EnvironmentError(
OSError: Error no file named config.json found in directory ./pretrained_model/stable-diffusion-v1-5.

**Comment by G-force78** [comment]
Try downloading this into ./pretrained_model/stable-diffusion-v1-5 its what I have https://huggingface.co/camenduru/champ/raw/main/stable-diffusion-v1-5/model_index.json

**Comment by XiaohangZhan** [comment]
`pretrained_model/stable-diffusion-v1-5/unet
mv unet_config.json config.json`

**Comment by Zejun-Yang** [comment]
> Try downloading this into ./pretrained_model/stable-diffusion-v1-5 its what I have https://huggingface.co/camenduru/champ/raw/main/stable-diffusion-v1-5/model_index.json

Thank you for kind reply. 
BTW, you can also manually download the full file from [stable-diffusion-v1-5](https://huggingface.co/runwayml/stable-diffusion-v1-5)
