### ISSUE TITLE
HF DEMO只能生成1秒的视频

### ISSUE THREAD

**Issue by goace** [Zejun-Yang/AniPortrait#125]
线上demo，我输入10s的音频，只生成了1s的视频，是我用的不对吗？

**Comment by h3ndrik** [comment]
I think that slider is number of frames, not number of seconds. So you'd need to put in something like 240 to generate 10s of video with a framerate of 24fps.

**Comment by goace** [comment]
@h3ndrik which slider are you referring to?
![image](https://github.com/Zejun-Yang/AniPortrait/assets/1522449/1c51cae9-340b-4696-8610-a460433c30a3)

**Comment by Zejun-Yang** [comment]
感谢关注我们的Hugging face项目。Length滑动条控制的是生成视频的帧数，对于30fps的视频，生成30帧对应1秒的视频。由于平台算力限制，为了降低用户等待时间，我们只能将生成帧数最高上限设置为90，即3秒。如需生成长视频，可部署源码。
