### ISSUE TITLE
What is the normal generation time?

### ISSUE THREAD

**Issue by iraymondking** [Zejun-Yang/AniPortrait#127]
A 3-second audio plus picture, it takes 1 hour to generate the video, the graphics card is Telsa m40. Is it normal?

**Comment by MisterT96** [comment]
Between 30 minutes and one hour 
One hour for one minute seems legit for me too (RTX 2080 TI and CUDA installed).
Somehow it seems that it uses CPU and no GPU for me. 
Did you find GPU mode?

**Comment by G-force78** [comment]
> A 3-second audio plus picture, it takes 1 hour to generate the video, the graphics card is Telsa m40. Is it normal?

No theres something wrong maybe the wrong onnxruntime-gpu build.  Try onnxruntime-gpu==1.17

**Comment by Zejun-Yang** [comment]
It takes two minutes to generate a 3s video on A100 without frame interpolation accelerating. And using -acc command can shorten the time cost to 50s.
