### ISSUE TITLE
ValueError: x and y arrays must be equal in length along interpolation axis.

### ISSUE THREAD

**Issue by gessyoo** [Zejun-Yang/AniPortrait#132]
I've encountered this error when trying to create the head pose file,  running for example,

`python -m scripts.generate_ref_pose --ref_video A:\climb.mp4 --save_path ./configs/inference/head_pose_temp/climb_pose.npy`

I'm made sure that the input videos are 512x512, 30 FPS .mp4 files.  Does the error signal that the head pose in the video is too extreme to detect and track with the pose aligner?  Is there a way to fix this error, or handle it gracefully so that the script does not crash?

![interpolation_error](https://github.com/Zejun-Yang/AniPortrait/assets/35972345/46779522-43e4-44cb-bbd1-b9594ac2f6e6)

**Comment by Zejun-Yang** [comment]
It's because that no human face was detected in one of the frames of the video. We have addressed this issue. You can update the file scripts/generate_ref_pose.py.
