### ISSUE TITLE
請問資源與生成時間問題

### ISSUE THREAD

**Issue by a801092005** [Zejun-Yang/AniPortrait#135]
這樣跑效能跟資源的狀況是正常的嗎?還要耗時15小時左右，音頻約20秒與一張圖片450x430 png檔
指令用python -m scripts.audio2vid --config ./configs/prompts/animation_audio.yaml -W 512 -H 512 -acc

![Snipaste_2024-04-23_00-20-53](https://github.com/Zejun-Yang/AniPortrait/assets/97590883/353ea9b8-3fa8-403d-8850-50073e37bbfc)

**Comment by Zejun-Yang** [comment]
我们在A100上，基于-W 512 -H 512 -acc指令的测试结果是：生成1秒钟视频需要处理10秒钟左右。3070 Ti在性能上可能无法实现更快速的处理。
您可以尝试如下参数，其中 -L 300表示生成300帧，即10秒的视频：
-W 384 -H 384 -acc --steps 20 -L 300
