### ISSUE TITLE
IndexError: list index out of range audio2vid 4 second clip

### ISSUE THREAD

**Issue by G-force78** [Zejun-Yang/AniPortrait#137]
(audio_chunks[-2], audio_chunks[-1]), dim=1
IndexError: list index out of range

Edit: changed chunk_duration to 2 and error is gone

**Comment by SystemErrorWang** [comment]
same problem here，would be grateful if anyone could provide helpful information

**Comment by cavalier501** [comment]
> same problem here，would be grateful if anyone could provide helpful information

I resolved the issue by changing chunk_duration at line 176 to a proper length. Hope this helps!
