### ISSUE TITLE
huggingface demo失效

### ISSUE THREAD

**Issue by kymlcode** [Zejun-Yang/AniPortrait#141]
你好大佬，https://huggingface.co/spaces/ZJYang/AniPortrait_official，在huggingface上demo貌似出错，无法通过api调用了，大佬有空可以解决一下吗，感谢🙏。
这是报错信息：
ValueError: The current space is in the invalid state: RUNTIME_ERROR. Please contact the owner to fix this.

**Comment by Zejun-Yang** [comment]
我看了下HF demo页面能正常运行，目前我们没关注用api调用HF接口的场景，不太清楚上述报错的原因。您可以尝试部署源码。
