### ISSUE TITLE
我的研究进展

### ISSUE THREAD

**Issue by daikankan** [Zejun-Yang/AniPortrait#143]
以下是一些效果展示，包括人脸驱动，语音驱动，表情姿态动作迁移等：

https://github.com/Zejun-Yang/AniPortrait/assets/20749514/a4bd2a06-6be8-4ecf-bfa3-337e5dcff4bb

https://github.com/Zejun-Yang/AniPortrait/assets/20749514/087b2023-67e9-41bf-bf31-204052889716

https://github.com/Zejun-Yang/AniPortrait/assets/20749514/053533eb-4237-4092-b224-cb62f6b03b59

**Comment by yixian3500** [comment]
第一个效果很好，是用的musetalk吗？参数是怎样的？

**Comment by daikankan** [comment]
> 第一个效果很好，是用的musetalk吗？参数是怎样的？

不是musetalk，是自研算法

**Comment by slacklife** [comment]
请问 audio2mesh.mp4  和 talk_emotion.mp4  分别是基于哪个工程实现的？
