### ISSUE TITLE
作者大大，请教训练问题

### ISSUE THREAD

**Issue by onedotone-wei** [Zejun-Yang/AniPortrait#145]
我看到训练分为两步，第一步训练生成dpr三个，第二步生成m一个
请问：
1.您是基本什么原因考虑，要将训练分开两个步骤？
2.如果仅训练第一步而不训练第二步，使用该模型后，生成的视频会是什么样的效果？
ps：由于硬件设备条件有限，再加上VFHQ  CelebV-HQ这种海量级数据，所以您能不能提前预知一下我，谢谢

**Comment by Zejun-Yang** [comment]
1、分两阶段训练的主要原因是受设备显存限制，40G的A100无法支持同时训练dprm四个模块。
2、不训练第二阶段时，生成的视频会有明显的抖动。

**Comment by onedotone-wei** [comment]
明白了，感谢
