### ISSUE TITLE
starting with “Audio driven” command remains at 0%

### ISSUE THREAD

**Issue by enjoykian** [Zejun-Yang/AniPortrait#146]
Hi and first of all thank you for such a great and powerful tool!

I have been running the neural network using “Self driven” and “Face reenacment” with no problems, however when I try to run in “Audio driven” mode the process does not move from 0%.

What could be my mistake ? 
OS win 10, i9-13900k, 64gb RAM, GPU RTX4080

**Comment by enjoykian** [comment]
Sorry, still after about 10 minutes the process moved to 4%.
It's strange that in other modes everything is moving much faster (20 seconds video is processed in a couple of minutes).
PS : sorry for my english

**Comment by enjoykian** [comment]
RE: using a custom head pose template solved this problem.
Thank's

**Comment by SeBL4RD** [comment]
I exactly have the same problem, 
something escapes me, if I put a reference pose, what's the point of using audio to video???? It seems weird to me, if sound and video don't match....

Ryzen 7 3700x, 32 gigs, 2070 Super 8 GB, 970 Evo+

**Comment by G-force78** [comment]
> I exactly have the same problem, something escapes me, if I put a reference pose, what's the point of using audio to video???? It seems weird to me, if sound and video don't match....
> 
> Ryzen 7 3700x, 32 gigs, 2070 Super 8 GB, 970 Evo+
> 
> EDIT: even with the template pose, it still takes me a long time.

There is no point really, I think the reason audio2vid was created is to try and generate authentic expressions in video via one-shot from the audio alone that has been trained on expressions. It just doesnt seem to work very well. You would be better off filming yourself speaking the words then generate the template from that to use in vid2vid or pose2vid.

**Comment by enjoykian** [comment]
I noticed that during video generation, no more than 1 or 2 percent of the GPU and 3 percent of the CPU is used. At the same time, a 30-second video in the “Self driven” mode took about 15 minutes to process. Is it possible to use more resources for faster generation? (I have Cuda installed)
