### ISSUE TITLE
install  requirements issue on Mac silicon

### ISSUE THREAD

**Issue by dobzhao** [Zejun-Yang/AniPortrait#147]
run the following command
```zsh
pip install -r requirements.txt
```

and get this ERROR:

> ERROR: Could not find a version that satisfies the requirement decord==0.6.0 (from versions: none)
> ERROR: No matching distribution found for decord==0.6.0

Platform:  Apple M2 Max
OS:  MacOS 14.4.1
python version:  3.9,  3.12 have the same issue

**Comment by Zejun-Yang** [comment]
We are sorry that AniPortrait does not support MacOS yet. #32
