### ISSUE TITLE
Audio driven works, but only 2 seconds.

### ISSUE THREAD

**Issue by ZeroHackz** [Zejun-Yang/AniPortrait#15]
### Great repository! thanks for sharing. Very clear read me, easily to set up!

_I'm have created an animation based on audio, but it only animates the first two seconds.. This is the command line, no errors:_

![Capture](https://github.com/Zejun-Yang/AniPortrait/assets/15729496/8a8e7e1e-89e3-425b-a7fe-ff297221de7b)

Animated video:
<table class="center">
<tr>
    <td width=50% style="border: none">
        <video controls autoplay loop src="https://github.com/Zejun-Yang/AniPortrait/assets/15729496/6854fd76-a9e5-45cc-8912-09f1a6d81bb5" muted="false"></video>
    </td>
</tr>
</table>

**Any tips, on getting the whole audio file (10 seconds) to be animated?**

**Comment by hatakeyama-poke** [comment]
Please increase the value of the -L argument in the execution command.

**Comment by Zejun-Yang** [comment]
> Please increase the value of the -L argument in the execution command.

Exactly. We have updated this tip in README.
