### ISSUE TITLE
SDXL Support?

### ISSUE THREAD

**Issue by matbee-eth** [Zejun-Yang/AniPortrait#157]
Does this support the AnimateDiff SDXL model out of the box or will it need some refactoring?

**Comment by gessyoo** [comment]
> Does this support the AnimateDiff SDXL model out of the box or will it need some refactoring?

I asked the same question a while ago.  The model was trained on SD 1.5 and so SDXL won't give good results.  I think the model would need to be re-trained on SDXL.  I've considered retraining the model but the training data is terabytes in size, and I've only a single GPU.

**Comment by Zejun-Yang** [comment]
Not support yet, sorry.
