### ISSUE TITLE
ReferenceNet Model in the Stage1

### ISSUE THREAD

**Issue by Janspiry** [Zejun-Yang/AniPortrait#158]
Hi, thanks for this repo.

The paper mentioned that you conducted two-stage training. In the first stage, the ReferenceNet and PoseGuider is trained using pictures and corresponding poses.  Can you add to this part of the model to the community?

**Comment by Zejun-Yang** [comment]
[pose_guider.pth](https://huggingface.co/ZJYang/AniPortrait/blob/main/pose_guider.pth) and [reference_unet.pth](https://huggingface.co/ZJYang/AniPortrait/blob/main/reference_unet.pth) are what you need.
