### ISSUE TITLE
X-portrait as source to improve aniportrait

### ISSUE THREAD

**Issue by ayu2hami** [Zejun-Yang/AniPortrait#159]
I found this video:
https://www.youtube.com/watch?v=VGxt5XghRdw

It's called x-portrait, the source code is not released yet, but...
I thought maybe the video could be somehow informative to improve aniportrait.
It seems to show good results and the overview of the workflow.

**Comment by Zejun-Yang** [comment]
We have also noticed this excellent work, thank you so much!
