### ISSUE TITLE
多张低显存卡解决方案是否存在

### ISSUE THREAD

**Issue by a624090359** [Zejun-Yang/AniPortrait#172]
我有8*16g的显卡，目前一张卡16g显存加载不了模型进行audio to video。
有没有办法多卡加载使用？
望回复，感谢！

**Comment by Zejun-Yang** [comment]
由于目前的模型采用串行分段生成的策略，所以暂时没办法多卡并行处理。你可以考虑将一段音频拆分成多段，在多张卡上生成视频后，再用插帧模型将视频片段串起来。
