### ISSUE TITLE
关于Stage2训练问题

### ISSUE THREAD

**Issue by onedotone-wei** [Zejun-Yang/AniPortrait#175]
目前Stage1训练了5万次，Stage2训练了1万次，validation生成出来的图片效果也不错，但是实际使用audio2vid时，肩膀部分呈白色而且抖动厉害，您之前也提到过，不训练第二阶段时，生成的视频会有明显的抖动

请问我这是训练次数不够呢？还是其他什么问题？

**Comment by Zejun-Yang** [comment]
可以尝试延长stage2的训练步数。另外由于肩膀没有显式的控制信号，长视频推理的时候，每一小段的肩膀姿态可能存在差异，因此视频会呈现出肩膀抖动的现象。您可以尝试在处理pose image的时候，加入肩膀的landmark。
