### ISSUE TITLE
ffmpeg required

### ISSUE THREAD

**Issue by cnkang** [Zejun-Yang/AniPortrait#21]
~/AniPortrait# python -m scripts.pose2vid --config ./configs/prompts/animation.yaml -W 512 -H 512 -L 64
Some weights of the model checkpoint were not used when initializing UNet2DConditionModel: 
 ['conv_norm_out.weight, conv_norm_out.bias, conv_out.weight, conv_out.bias']
/usr/local/lib/python3.10/dist-packages/torch/_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1711601336.882610    1144 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1711601336.993011    1252 gl_context.cc:357] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 550.54.15), renderer: Tesla T4/PCIe/SSE2
W0000 00:00:1711601337.025092    1144 face_landmarker_graph.cc:174] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
I0000 00:00:1711601337.098167    1144 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1711601337.154676    1262 gl_context.cc:357] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 550.54.15), renderer: Tesla T4/PCIe/SSE2
pose video has 1794 frames, with 30 fps
/root/AniPortrait/src/pipelines/pipeline_pose2vid_long.py:408: FutureWarning: Accessing config attribute `in_channels` directly via 'UNet3DConditionModel' object attribute is deprecated. Please access 'in_channels' over 'UNet3DConditionModel's config object instead, e.g. 'unet.config.in_channels'.
  num_channels_latents = self.denoising_unet.in_channels
100%|████████████████████████████████████████████████████████████████████████████████████████████| 25/25 [09:03<00:00, 21.74s/it]
100%|████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:10<00:00,  6.07it/s]
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/AniPortrait/scripts/pose2vid.py", line 199, in <module>
    main()
  File "/root/AniPortrait/scripts/pose2vid.py", line 189, in main
    ffmpeg.input(pose_video_path).output(audio_output, acodec='copy').run()
  File "/usr/local/lib/python3.10/dist-packages/ffmpeg/_run.py", line 313, in run
    process = run_async(
  File "/usr/local/lib/python3.10/dist-packages/ffmpeg/_run.py", line 284, in run_async
    return subprocess.Popen(
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'

**Comment by Zejun-Yang** [comment]
https://github.com/kkroening/ffmpeg-python/issues/251
Maybe you can refer this issue. I hope this will be helpful!

**Comment by kieojk** [comment]
May be you can try `conda install -c conda-forge ffmpeg`. It works for me

**Comment by wangwenqiao666** [comment]
Linux need ues **sudo apt install ffmpeg**
