### ISSUE TITLE
video2video，源video需要和ref_image对齐吗？

### ISSUE THREAD

**Issue by wly-ai-bj** [Zejun-Yang/AniPortrait#27]
提供参考video和参考图片，生成新的视频。
1）可以是video2video，这里有什么要求吗？
2）分2步，先video2pose，得到pose序列；再pose2video。

不管哪种方法，都有一个问题，就是“参考video和参考图片可以任意搭配吗？二者需要有什么对齐关系吗？比如上下位置要一致？”

从网络上随意找的动图素材（.mp4），选择代码中给的ref_image。但效果大打折扣。

**Comment by FacePoluke** [comment]
结果发出来看看？我也跑了一些素材，发现代码会有以下要求：
1. ref image最好是自然表情（无张嘴）
2. source video要crop成square，因为网络的输入会把视频resize成512x512，不crop的话人脸会被挤压或者拉宽（可能不符合训练的分布）

**Comment by Zejun-Yang** [comment]
将参考图片和参考视频处理成半身肖像的形式，尺寸作为正方形即可。可以参照demo中的样式，不需要严格对齐图片和视频的头部位置。

**Comment by wly-ai-bj** [comment]
> 结果发出来看看？我也跑了一些素材，发现代码会有以下要求：
> 
> 1. ref image最好是自然表情（无张嘴）
> 2. source video要crop成square，因为网络的输入会把视频resize成512x512，不crop的话人脸会被挤压或者拉宽（可能不符合训练的分布）

谢谢，我按照你的建议进行了crop，还是会有些结果有点恐怖😱

https://github.com/Zejun-Yang/AniPortrait/assets/58155968/610e6230-cee5-4851-b6cb-5d38ab05f289


https://github.com/Zejun-Yang/AniPortrait/assets/58155968/3e255364-20bd-4f5e-83f4-71bc0e79472d

**Comment by hben35096** [comment]
@wly-ai-bj 
Let's try placing the facial features of the person in the first frame of the video at the center of a 3x3 grid.
![image](https://github.com/Zejun-Yang/AniPortrait/assets/139383150/96c607a8-7b5a-41ee-8ad5-6afa2a6d2c05)

**Comment by Zejun-Yang** [comment]
> > 结果发出来看看？我也跑了一些素材，发现代码会有以下要求：
> > 
> > 1. ref image最好是自然表情（无张嘴）
> > 2. source video要crop成square，因为网络的输入会把视频resize成512x512，不crop的话人脸会被挤压或者拉宽（可能不符合训练的分布）
> 
> 谢谢，我按照你的建议进行了crop，还是会有些结果有点恐怖😱
> 
>  image2_qie_512x512_3_1122_noaudio.mp4 
>  image2_zhenhuan_512x512_3_1122_noaudio.mp4


https://github.com/Zejun-Yang/AniPortrait/assets/21038147/c8dad442-5851-4133-8966-cac21c39dfd1

https://github.com/Zejun-Yang/AniPortrait/assets/21038147/fc0e566f-e4d3-4e32-89c2-205ace44ec22

我们更新了新的姿态重定向策略，现在ref_image可以与source video存在较大姿态差异。

**Comment by wangxihao** [comment]
> > > 结果发出来看看？我也跑了一些素材，发现代码会有以下要求：
> > > 
> > > 1. ref image最好是自然表情（无张嘴）
> > > 2. source video要crop成square，因为网络的输入会把视频resize成512x512，不crop的话人脸会被挤压或者拉宽（可能不符合训练的分布）
> > 
> > 
> > 谢谢，我按照你的建议进行了crop，还是会有些结果有点恐怖😱
> > image2_qie_512x512_3_1122_noaudio.mp4
> > image2_zhenhuan_512x512_3_1122_noaudio.mp4
> 
>  ref_img_test1_512x512_3_1515_noaudio.mp4 
>  ref_img_test2_512x512_3_1523_noaudio.mp4 
> 我们更新了新的姿态重定向策略，现在ref_image可以与source video存在较大姿态差异。

你好，这个新的姿态重定向策略代码实在video2video吗
