### ISSUE TITLE
No PositionNet

### ISSUE THREAD

**Issue by newzaungo3** [Zejun-Yang/AniPortrait#28]
Hi I check that in diffusers.models.embeddings version 0.24.0 has no Positionet function inside. Can you suggest me about how to fix this error?

`ImportError: cannot import name 'PositionNet' from 'diffusers.models.embeddings'`

**Comment by FredWe** [comment]
@newzaungo3  Have met same issue, any advices ?

**Comment by newzaungo3** [comment]
@FredWe Hi, I manually import PositionNet from https://github.com/huggingface/diffusers/blob/v0.24.0-release/src/diffusers/models/embeddings.py#L720 in branch version v0.24.0-release and it's working.
