### ISSUE TITLE
how to generate pose_temp.npy

### ISSUE THREAD

**Issue by guyanxiao** [Zejun-Yang/AniPortrait#3]
Thanks for you great work. 
I didn't found any place to generate pose_temp.npy which I want to use my own video to generate the pose.
Would you like to let me know how to generate pose_temp.npy?
Thanks a lot.

**Comment by Zejun-Yang** [comment]
Thank you for your interest! If you want to animate a portrait with your own video, you can use vid2vid.py for temporary. And we will update the code for generating pose_temp.npy latter.

**Comment by Zejun-Yang** [comment]
Already update the project, please pull the latest version.

**Comment by guyanxiao** [comment]
Thanks a lot.
