### ISSUE TITLE
是否支持流式输出

### ISSUE THREAD

**Issue by qq345736500** [Zejun-Yang/AniPortrait#30]

**Comment by ZeroHackz** [comment]
> _No description provided._

?

**Comment by ApolloRay** [comment]
他这个推理时间很长，1000多帧推理时间要1个小时。目前还没见到一个可以流式输出唇动的模型。

**Comment by ApolloRay** [comment]
> _No description provided._

能加速的方法，大概是把sd1.5替换成turbo模型，时间能缩80%。一帧视频的推理时间要降噪很多步，文生图512*512分辨率目前最快的大概是90ms，1s如果只有20帧，推理时间都要在接近2秒多。推理跟不上输出的速度。

**Comment by jsoncode** [comment]
流式输出，你可以一下考虑facefusion换脸软件是否满足

**Comment by Zejun-Yang** [comment]
很抱歉，目前不支持。
