### ISSUE TITLE
pip install onnxruntime-gpu 失败

### ISSUE THREAD

**Issue by taozhiyuai** [Zejun-Yang/AniPortrait#33]
pip install onnxruntime-gpu

Changes
1.17.1
Release Notes : https://github.com/Microsoft/onnxruntime/releases/tag/v1.17.1
1.17.0
Release Notes : https://github.com/Microsoft/onnxruntime/releases/tag/v1.17.0
1.16.0
Release Notes : https://github.com/Microsoft/onnxruntime/releases/tag/v1.16.0
1.15.0
Release Notes : https://github.com/Microsoft/onnxruntime/releases/tag/v1.15.0

以上版本安装都失败了.  MAC M3 MAX上安装的

**Comment by moluuser** [comment]
https://github.com/microsoft/onnxruntime/issues/12252#issuecomment-1190562227
看起来无法解决
