### ISSUE TITLE
参考图输入尺寸要求

### ISSUE THREAD

**Issue by dengfenglai321** [Zejun-Yang/AniPortrait#34]
基于参考图和人脸mark序列生成视频，对于参考图尺寸是否有要求？ 如果尺寸过大，resize到512*512去推理生成，人脸脸型会扭曲

**Comment by Zejun-Yang** [comment]
可以手动将图片裁剪成肩部以上的肖像形态，并确保尺寸为正方形，参照demo。确保人脸在图像中占比较大。
