### ISSUE TITLE
推理结果为噪声

### ISSUE THREAD

**Issue by fredkingdom** [Zejun-Yang/AniPortrait#40]
>  solo_solo_pose1_512x512_3_1438_noaudio.mp4 
> 我们复现了您反馈的问题。 触发条件没有正确加载我们预训练权重，导致模型参数跟我们的任务不匹配。 您可以重新下载我们的预训练模型，并确保其位于正确路径下，详情参考README.md。 https://huggingface.co/ZJYang/AniPortrait/tree/main

感谢您的回复，请问复现的这段视频是哪部分模型参数没有加载正确呢？我参考了本repo中的预训练模型目录，我的目录如下，看上去和您给的readme一致：
![微信截图_20240329151007](https://github.com/Zejun-Yang/AniPortrait/assets/41713524/4177e8c4-0e12-40a1-9b5c-c2f2924aacd3)

_Originally posted by @fredkingdom in https://github.com/Zejun-Yang/AniPortrait/issues/35#issuecomment-2026791762_

**Comment by Zejun-Yang** [comment]
可以检查模型文件大小是否正常，当git lfs clone过程存在异常时，可能出现文件下载不完整的问题。

**Comment by fredkingdom** [comment]
> 可以检查模型文件大小是否正常，当git lfs clone过程存在异常时，可能出现文件下载不完整的问题。

请问我需要下载链接中的全部权重文件，还是仅需下载readme中列出的如下权重文件呢？
```
./pretrained_weights/
|-- image_encoder
|   |-- config.json
|   `-- pytorch_model.bin
|-- sd-vae-ft-mse
|   |-- config.json
|   |-- diffusion_pytorch_model.bin
|   `-- diffusion_pytorch_model.safetensors
|-- stable-diffusion-v1-5
|   |-- feature_extractor
|   |   `-- preprocessor_config.json
|   |-- model_index.json
|   |-- unet
|   |   |-- config.json
|   |   `-- diffusion_pytorch_model.bin
|   `-- v1-inference.yaml
|-- wav2vec2-base-960h
|   |-- config.json
|   |-- feature_extractor_config.json
|   |-- preprocessor_config.json
|   |-- pytorch_model.bin
|   |-- README.md
|   |-- special_tokens_map.json
|   |-- tokenizer_config.json
|   `-- vocab.json
|-- audio2mesh.pt
|-- denoising_unet.pth
|-- motion_module.pth
|-- pose_guider.pth
`-- reference_unet.pth
```

**Comment by Zejun-Yang** [comment]
建议下载全部权重，以防readm存在纰漏。

**Comment by fredkingdom** [comment]
问题已经解决，似乎是环境配置的问题。
