### ISSUE TITLE
UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.

### ISSUE THREAD

**Issue by BearSolitarily** [Zejun-Yang/AniPortrait#54]
最后一步运行报错了，本人是windows系统，AMD显卡以及驱动。
最后这里报错：没有找到英伟达的驱动。
我查了一下AMD的GPU是不支持CUDA的

我是不是寄了
![2T{YFFU~NDSDNEJH57%EN_I](https://github.com/Zejun-Yang/AniPortrait/assets/56347949/3f7e6653-0652-4cc7-95eb-3df09973df46)

**Comment by Zejun-Yang** [comment]
AMD应该不兼容CUDA，可以尝试使用云服务器部署体验。
