### ISSUE TITLE
Data preparation error

### ISSUE THREAD

**Issue by 1595813520** [Zejun-Yang/AniPortrait#55]
`WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1711775950.511664   83072 task_runner.cc:85] GPU suport is not available: INTERNAL: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:77) display != EGL_NO_DISPLAYeglGetDisplay() returned error 0x300c
W0000 00:00:1711775950.512722   83072 face_landmarker_graph.cc:174] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
I0000 00:00:1711775950.569749   83072 task_runner.cc:85] GPU suport is not available: INTERNAL: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:77) display != EGL_NO_DISPLAYeglGetDisplay() returned error 0x300c`

请问这是怎么回事呢？是Mediapipe或TensorFlow的底层实现有问题吗？我是按照readme配置的环境，前面的三个推理都能正常运行。但运行 python -m scripts.preprocess_dataset 来处理hdtf数据集时时出现如上所示的报错，网上搜不到类似的情况和解决方法，只好冒昧来请教作者，非常感谢

**Comment by 1595813520** [comment]
如图所示
![微信图片_20240330152354](https://github.com/Zejun-Yang/AniPortrait/assets/152386277/7fd0682a-7d8e-44ab-a9cc-dfdb3910ef19)

**Comment by FacePoluke** [comment]
我也遇到了，用cpu模式就好了，face_landmarker_v2_with_blendshapes这个任务只支持cpu跑

**Comment by 1595813520** [comment]
> 我也遇到了，用cpu模式就好了，face_landmarker_v2_with_blendshapes这个任务只支持cpu跑

原来如此，解决啦，非常感谢~顺便问下，整个数据处理都是在cpu上进行的吗？那应该很慢吧

**Comment by 1595813520** [comment]
> 我也遇到了，用cpu模式就好了，face_landmarker_v2_with_blendshapes这个任务只支持cpu跑

感谢您的解答！！请问具体是如何操作的呢？我改变了环境变量来指定只使用cpu：
export CUDA_VISIBLE_DEVICES=-1
export TF_FORCE_GPU_ALLOW_GROWTH=true
但仍然报错：INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
I0000 00:00:1711794813.234487   94528 task_runner.cc:85] GPU suport is not available: INTERNAL: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:77) display != EGL_NO_DISPLAYeglGetDisplay() returned error 0x300c
看起来程序仍然在尝试使用 GPU 相关的操作orz
期待您的回复❀

**Comment by FacePoluke** [comment]
确保 utils/mp_models 下的模型没动过，然后mp_utils.py的这行 是CPU模式 https://github.com/Zejun-Yang/AniPortrait/blob/4e6c6aafc77d1285732008b536e025e5412a4550/src/utils/mp_utils.py#L24 这一行还有一个bug，把后面的[:600, 650:1350]删掉。https://github.com/Zejun-Yang/AniPortrait/blob/4e6c6aafc77d1285732008b536e025e5412a4550/scripts/preprocess_dataset.py#L99 其他地方我没有改动，可以正常跑通

**Comment by 1595813520** [comment]
不好意思作者，看到您关闭了这个issue，但我还是没有解决这个问题，我使用的ssh远程服务器，ubuntu系统，不知道和报错有没有关系？代码没有任何变动，报错为：GPU suport is not available: INTERNAL: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:77) display != EGL_NO_DISPLAYeglGetDisplay() returned error 0x300c
我在本地电脑上（windows系统）也运行不起来，报错是： Sets FaceBlendshapesGraph acceleration to xnnpack by default.    INFO: Created TensorFlow Lite XNNPACK delegate for CPU.

**Comment by 1595813520** [comment]
本地电脑的报错：
![image](https://github.com/Zejun-Yang/AniPortrait/assets/152386277/9f00a6ac-bfd9-479b-8be2-334f75fbd227)

**Comment by Zejun-Yang** [comment]
> 确保 utils/mp_models 下的模型没动过，然后mp_utils.py的这行 是CPU模式
> 
> https://github.com/Zejun-Yang/AniPortrait/blob/4e6c6aafc77d1285732008b536e025e5412a4550/src/utils/mp_utils.py#L24
> 
> 这一行还有一个bug，把后面的[:600, 650:1350]删掉。
> https://github.com/Zejun-Yang/AniPortrait/blob/4e6c6aafc77d1285732008b536e025e5412a4550/scripts/preprocess_dataset.py#L99
> 
> 其他地方我没有改动，可以正常跑通

这是我们的项目开发成员，您可以参考他的答复。

**Comment by 1595813520** [comment]
> 确保 utils/mp_models 下的模型没动过，然后mp_utils.py的这行 是CPU模式
> 
> https://github.com/Zejun-Yang/AniPortrait/blob/4e6c6aafc77d1285732008b536e025e5412a4550/src/utils/mp_utils.py#L24
> 
> 这一行还有一个bug，把后面的[:600, 650:1350]删掉。
> https://github.com/Zejun-Yang/AniPortrait/blob/4e6c6aafc77d1285732008b536e025e5412a4550/scripts/preprocess_dataset.py#L99
> 
> 其他地方我没有改动，可以正常跑通

感谢您的回复，我使用的ssh远程连接服务器，ubuntu系统，不知道和报错有没有关系？代码没有任何变动。
我在本地电脑上（windows系统）也运行不起来，报错是： Sets FaceBlendshapesGraph acceleration to xnnpack by default. INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
![image](https://github.com/Zejun-Yang/AniPortrait/assets/152386277/2f2b03b5-7b45-4685-baf2-e61c198151d4)

**Comment by FacePoluke** [comment]
你这看着好像没有报错，请检查一下你的图片格式，是jpg还是png。还有视频目录组织方式，这份代码适用input_dir下多个子目录，每个子目录下是一系列png图片。如果与这个格式不对，请自己修改代码适配

**Comment by 1595813520** [comment]
> 你这看着好像没有报错，请检查一下你的图片格式，是jpg还是png。还有视频目录组织方式，这份代码适用input_dir下多个子目录，每个子目录下是一系列png图片。如果与这个格式不对，请自己修改代码适配

好的，我解决啦，非常感谢您的回答！！我输入的视频目录是：
![image](https://github.com/Zejun-Yang/AniPortrait/assets/152386277/fb61d5d8-689b-4457-8fd3-d3b89268ce54)

修改为逐帧提取，请问处理好的输出是这种格式吗？每张png图片对应有四个文件：
![image](https://github.com/Zejun-Yang/AniPortrait/assets/152386277/ddca222a-85c8-4bcd-86af-79e07957d70f)

**Comment by FacePoluke** [comment]
是的

**Comment by triton99** [comment]
Hi @FacePoluke ,
How can I use preprocess_dataset.py for the CelebV-HQ dataset? This code seems to be used for the image directory.
![image](https://github.com/Zejun-Yang/AniPortrait/assets/53249939/9fc17da9-52b9-4260-9f2b-31b6b7edd50e)

Thank you.

**Comment by 1595813520** [comment]
> Hi @FacePoluke , How can I use preprocess_dataset.py for the CelebV-HQ dataset? This code seems to be used for the image directory. ![image](https://private-user-images.githubusercontent.com/53249939/325141819-9fc17da9-52b9-4260-9f2b-31b6b7edd50e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMTQyODcsIm5iZiI6MTcxNjExMzk4NywicGF0aCI6Ii81MzI0OTkzOS8zMjUxNDE4MTktOWZjMTdkYTktNTJiOS00MjYwLTlmMmItMzFiNmI3ZWRkNTBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDEwMTk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExYTgzNWZmZmI3NWVjNmExODNkYzllNTViZWM0OTgxYzM4MGRkMDBlNjU4NGU0MjQ5N2Y1ZGZhZWUyNWM2YjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CyMnT9MPg8B4LjhQzojPIMalxY4HE5RHJEXTyzgClwc)
> 
> Thank you.

> Here's my modified preprocess_dataset.py file for the videos folder：
`import os
import argparse

import numpy as np
import cv2
from tqdm import tqdm
import glob
import json

from src.utils.mp_utils  import LMKExtractor


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input_dir", type=str, default='/data/AniPortrait/pretrained_model/video', help='path of dataset')
    parser.add_argument("--output_dir", type=str, default='/data/AniPortrait/pretrained_model/pre_video',  help='path to save extracted annotations')
    parser.add_argument("--training_json", type=str, default='/data/AniPortrait/configs/train/training_data.json',  help='path to save training json')
    args = parser.parse_args()
    return args



def generate_training_json_mesh(video_dir, face_info_dir, res_json_path, min_clip_length=30):
    video_name_list = sorted(os.listdir(face_info_dir))
    res_data_dic = {}

    pbar = tqdm(range(len(video_name_list)))


    for video_index, video_name in enumerate(video_name_list):
        pbar.update(1)

        tem_dic = {}
        tem_tem_dic = {}
        video_clip_dir = os.path.join(video_dir, video_name)
        lmks_clip_dir = os.path.join(face_info_dir, video_name)

        video_clip_num = 1
        video_data_list = []

        frame_path_list = sorted(glob.glob(os.path.join(video_clip_dir, '*.png')))
        lmks_path_list = sorted(glob.glob(os.path.join(lmks_clip_dir, '*lmks.npy')))

        min_len = min(len(frame_path_list), len(lmks_path_list))
        frame_path_list = frame_path_list[:min_len]
        lmks_path_list = lmks_path_list[:min_len]


        if min_len < min_clip_length:
            info = 'min length: {} {}'.format(video_name, min_len)
            video_clip_num -= 1
            continue

        first_frame_basename = os.path.basename(frame_path_list[0]).split('.')[0]
        first_lmks_basename = os.path.basename(lmks_path_list[0]).split('_')[0]
        last_frame_basename = os.path.basename(frame_path_list[-1]).split('.')[0]
        last_lmks_basename = os.path.basename(lmks_path_list[-1]).split('_')[0]
    
        if (first_frame_basename != first_lmks_basename) or (last_frame_basename != last_lmks_basename):
            info = 'different length skip: {} , length {}/{}, frame/lmks'.format(video_name, len(frame_path_list), len(lmks_path_list))
            video_clip_num -= 1
            continue

        frame_name_list = [os.path.join(video_name, os.path.basename(item)) for item in frame_path_list]

        tem_tem_dic['frame_name_list'] = frame_name_list
        tem_tem_dic['frame_path_list'] = frame_path_list
        tem_tem_dic['lmks_list'] = lmks_path_list
        video_data_list.append(tem_tem_dic)

        tem_dic['video_clip_num'] = video_clip_num
        tem_dic['clip_data_list'] = video_data_list
        res_data_dic[video_name] = tem_dic

    with open(res_json_path, 'w') as f:
        json.dump(res_data_dic, f)

# 主函数
def main():
    args = parse_args()

    os.makedirs(args.output_dir, exist_ok=True)
    video_files = sorted(glob.glob(os.path.join(args.input_dir, "*.mp4")))

    lmk_extractor = LMKExtractor()

    pbar = tqdm(range(len(video_files)), desc="processing ...")
    for video_file in video_files:
        pbar.update(1)
        video_name = os.path.splitext(os.path.basename(video_file))[0]
        output_subdir = os.path.join(args.output_dir, video_name)
        os.makedirs(output_subdir, exist_ok=True)

        cap = cv2.VideoCapture(video_file)
        frame_num = 0

        while cap.isOpened():
            ret, frame = cap.read()
            if not ret:
                break

            img_file = os.path.join(output_subdir, f"{video_name}_{frame_num:04d}.png")
            cv2.imwrite(img_file, frame)

            result = lmk_extractor(frame)

            if result is not None:
                lmks_output_file = os.path.join(output_subdir, f"{video_name}_{frame_num:04d}_lmks.npy")
                lmks3d_output_file = os.path.join(output_subdir, f"{video_name}_{frame_num:04d}_lmks3d.npy")
                trans_mat_output_file = os.path.join(output_subdir, f"{video_name}_{frame_num:04d}_trans_mat.npy")
                bs_output_file = os.path.join(output_subdir, f"{video_name}_{frame_num:04d}_bs.npy")

                np.save(lmks_output_file, result['lmks'].astype(np.float32))
                np.save(lmks3d_output_file, result['lmks3d'].astype(np.float32))
                np.save(trans_mat_output_file, result['trans_mat'].astype(np.float32))
                np.save(bs_output_file, np.array(result['bs']).astype(np.float32))

            frame_num += 1

        cap.release()

    generate_training_json_mesh(args.input_dir, args.output_dir, args.training_json, min_clip_length=30)

if __name__ == "__main__":
    main()`
