### ISSUE TITLE
How much GPU ram it requires? 

### ISSUE THREAD

**Issue by fralik** [Zejun-Yang/AniPortrait#58]
I wonder if you have a rough estimate of required GPU memory. Trying to figure this out before running the code.
Thanks!

**Comment by Zejun-Yang** [comment]
It requires approximately 10,000MB of GPU memory during inference.

**Comment by fralik** [comment]
I should have specified which script I was running. Audio2video seems to require more. I wasn't able to run it on 15Gb of gpu. Running it now and it reports 16 Gb:
![image](https://github.com/Zejun-Yang/AniPortrait/assets/191278/7554a5a0-0863-45c9-a72c-7c7c4bfc57d2)

**Comment by Zejun-Yang** [comment]
> I should have specified which script I was running. Audio2video seems to require more. I wasn't able to run it on 15Gb of gpu. Running it now and it reports 16 Gb: ![image](https://private-user-images.githubusercontent.com/191278/318187626-7554a5a0-0863-45c9-a72c-7c7c4bfc57d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4MDI5MTQsIm5iZiI6MTcxMTgwMjYxNCwicGF0aCI6Ii8xOTEyNzgvMzE4MTg3NjI2LTc1NTRhNWEwLTA4NjMtNDVjOS1hNzJjLTdjN2M0YmZjNTdkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMzMFQxMjQzMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YTA2OTE0NTAwMDk1M2FjYWY2YmI3N2Q2Y2Y1ZDczNTg1NGI2ZGNmNzYzMzZjZTQ3MmNjODljYTUyM2FlZTg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RR_iXahMvovyWaYLJ42jOjJnacO-5Jbc3VdRgH6WwaE)

Some software also occupies GPU memory, a common occurrence on Windows OS. You can try to turn them off to free up additional GPU memory.

**Comment by fralik** [comment]
I was running on Google Colab. It's Linux and pretty clutter free. From my experience, running different scripts on A100 (40 gb ram) works fine. Running on V100 (16 gb ram) most likely will give an out of memory error at some point.
