### ISSUE TITLE
How far can this approach go with more training data vs a pure audio2video model? 

### ISSUE THREAD

**Issue by KazamaShizuo** [Zejun-Yang/AniPortrait#62]
This is great work from Tencent! As acknowledged in the Paper this is using Audio2Lmk <> Lmk2Video. In order for better facial expressions and better facial features including teeth,lips,and cheeks is training on more facial expression video data worth trying or does more work need to be done at Audio2Lmk stage?

**Comment by Zejun-Yang** [comment]
Thank you for your interest!  To enhance facial details, we aim to optimize the framework instead of expanding the training data. We will update the code as we make progress.
