### ISSUE TITLE
nice work, but issue about audio2video 效果不错，但是只能生成8秒的视频，请问如何解决

### ISSUE THREAD

**Issue by mingweihehehe** [Zejun-Yang/AniPortrait#66]
I tested audio2video on colab, the effect is good, but only 8 seconds of video can be generated, may I ask how to fix this problem?

我在colab上测试 audio2video，效果不错，但是只能生成8秒的视频，请问如何修复这个问题。

test link:https://colab.research.google.com/github/camenduru/AniPortrait-jupyter/blob/main/AniPortrait_audio2vid_jupyter.ipynb#scrollTo=OboTn0sUHuAD

**Comment by mingweihehehe** [comment]
给到了38秒左右的音频，8秒之后的输出视频都是为空，8秒之前效果正常

**Comment by Zejun-Yang** [comment]
!python -m scripts.audio2vid --config ./configs/prompts/animation_audio.yaml -W 512 -H 512 -L 256

以上是您使用的指令，L=256表示输出视频为256帧，结合fps=30，则视频时长为256/30=8.5s，符合预期。
您可以修改L为38*30=1140或者直接不指定L的值，即可生成与语音长度一致的视频。

**Comment by mingweihehehe** [comment]
> !python -m scripts.audio2vid --config ./configs/prompts/animation_audio.yaml -W 512 -H 512 -L 256
> 
> 以上是您使用的指令，L=256表示输出视频为256帧，结合fps=30，则视频时长为256/30=8.5s，符合预期。 您可以修改L为38*30=1140或者直接不指定L的值，即可生成与语音长度一致的视频。

谢谢答复，如果想不指定L值，具体是设置留空吗还是-1或0？

**Comment by Zejun-Yang** [comment]
> > !python -m scripts.audio2vid --config ./configs/prompts/animation_audio.yaml -W 512 -H 512 -L 256
> > 以上是您使用的指令，L=256表示输出视频为256帧，结合fps=30，则视频时长为256/30=8.5s，符合预期。 您可以修改L为38*30=1140或者直接不指定L的值，即可生成与语音长度一致的视频。
> 
> 谢谢答复，如果想不指定L值，具体是设置留空吗还是-1或0？

直接留空，例如
!python -m scripts.audio2vid --config ./configs/prompts/animation_audio.yaml -W 512 -H 512
