### ISSUE TITLE
Inference is too slow on L4 GPU Cloud (24GB)

### ISSUE THREAD

**Issue by Mrkomiljon** [Zejun-Yang/AniPortrait#67]
Hi @Zejun-Yang , thank you for your great work!
I was trying to inference your model by given default settings even without changing the default files. However I am facing with a problem during inference, which is quite slow. Is it expected behavior when I run the following:
```
python -m scripts.pose2vid --config ./configs/prompts/animation.yaml -W 512 -H 512
```
I downloaded all the weights from given sources and run the above code. ETA time shows around 3 hours. Could you guide me on inferencing or devices I should be using for inference. 
Thank you!

**Comment by Zejun-Yang** [comment]
This framework is constructed on the Diffusion model, thus it will inevitably be slow during inference. We will optimize the framework in the future.
