### ISSUE TITLE
Please access 'in_channels' over 'UNet3DConditionModel's config object instead

### ISSUE THREAD

**Issue by TomiTom1234** [Zejun-Yang/AniPortrait#68]
I installed everything perfectly. But when I run the command : 
`python -m scripts.pose2vid --config ./configs/prompts/animation.yaml -W 512 -H 512`

The following message appears and the process stops here forever:
`E:\AI\AniPortrait\AniPortrait\src\pipelines\pipeline_pose2vid_long.py:408: FutureWarning: Accessing config attribute `in_channels` directly via 'UNet3DConditionModel' object attribute is deprecated. Please access 'in_channels' over 'UNet3DConditionModel's config object instead, e.g. 'unet.config.in_channels'.
  num_channels_latents = self.denoising_unet.in_channels
  0%|                                                                                           | 0/25 [00:00<?, ?it/s]`

Any idea what I should do as a solution?

**Comment by Zejun-Yang** [comment]
This is an unnecessary warning, and you can ignore it.
