### ISSUE TITLE
lips move too fast

### ISSUE THREAD

**Issue by guyanxiao** [Zejun-Yang/AniPortrait#7]
I am trying to using audio2vid to generate some audio driven video and I found the lips move too fast and it looks not so nature.
I wondered that if it's possible to smooth the lips and made the video more nature?
Thanks for your great work and looks good for the video generated.

https://github.com/Zejun-Yang/AniPortrait/assets/32560672/c92a3c55-e757-451d-8934-b535b020dbf3

**Comment by Zejun-Yang** [comment]
You can apply smoothing to the pred mesh after https://github.com/Zejun-Yang/AniPortrait/blob/bfa15742af3233c297c72b8bb5d7637c5ef5984a/scripts/audio2vid.py#L155, similar to what is done at https://github.com/Zejun-Yang/AniPortrait/blob/bfa15742af3233c297c72b8bb5d7637c5ef5984a/scripts/generate_ref_pose.py#L85

**Comment by guyanxiao** [comment]
Thanks a lot.
