### ISSUE TITLE
how to  get neutral mesh from？

### ISSUE THREAD

**Issue by DavidKong96** [Zejun-Yang/AniPortrait#71]
hi,thanks for sharing your great work!
i'm thinking about how to get neutral mesh from a image or video when training audio2mesh model.

**Comment by FacePoluke** [comment]
We use data of one person for training, so we manually specify the neutral face frame.

**Comment by DavidKong96** [comment]
> We use data of one person for training, so we manually specify the neutral face frame.
Thanks for your reply ！but i still have some questions about that.

only one person for training audio2mesh model? Does this generalize well enough to reason about arbitrary characters? 

and when i try to use MP to get 3d face mesh from a wild face , the mesh looks like this...  
![image](https://github.com/Zejun-Yang/AniPortrait/assets/35676173/c2c435d9-5c33-4062-bd33-c143273d98a7)

![image](https://github.com/Zejun-Yang/AniPortrait/assets/35676173/5e160f59-0c21-4b19-a5af-b16ff9fdf9a7)

Won't this affect the accuracy of the results?

**Comment by FacePoluke** [comment]
We learn offset mesh. In inference stage, we add the offset to the neutral mesh of the given character. By default, we assume that the reference image represents a neutral facial expression. If a reference image with a significant facial expression is provided, the driving effect may not be optimal. If you have a video with the ID of this reference image, you can use the code in vid2vid to extract its neutral mesh (verts_arr[min_bs_idx]).  https://github.com/Zejun-Yang/AniPortrait/blob/888dce3a6b576a486210b54e2cad45facc40196b/scripts/vid2vid.py#L174

**Comment by DavidKong96** [comment]
> We learn offset mesh. In inference stage, we add the offset to the neutral mesh of the given character. By default, we assume that the reference image represents a neutral facial expression. If a reference image with a significant facial expression is provided, the driving effect may not be optimal. If you have a video with the ID of this reference image, you can use the code in vid2vid to extract its neutral mesh (verts_arr[min_bs_idx]).
> 
> https://github.com/Zejun-Yang/AniPortrait/blob/888dce3a6b576a486210b54e2cad45facc40196b/scripts/vid2vid.py#L174

thank you so much,  i will try
