### ISSUE TITLE
python -m scripts.pose2vid --config ./configs/prompts/animation.yaml -W 512 -H 512 执行报错

### ISSUE THREAD

**Issue by FLH1030** [Zejun-Yang/AniPortrait#76]
执行命令“python -m scripts.pose2vid --config ./configs/prompts/animation.yaml -W 512 -H 512”报错
ncl --enable-runtime-cpudetect --enable-shared --enable-vaapi --enable-vdpau --enable-version3 --enable-xlib
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
./configs/inference/pose_videos/solo_pose.mp4: No such file or directory
Traceback (most recent call last):
  File "/data/workpace/AniPortrait/.conda/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/workpace/AniPortrait/.conda/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data/workpace/AniPortrait/scripts/pose2vid.py", line 200, in <module>
    main()
  File "/data/workpace/AniPortrait/scripts/pose2vid.py", line 190, in main
    ffmpeg.input(pose_video_path).output(audio_output, acodec='copy').run()
  File "/data/workpace/AniPortrait/.conda/lib/python3.10/site-packages/ffmpeg/_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)

**Comment by Zejun-Yang** [comment]
貌似是视频没有音频？

**Comment by FLH1030** [comment]
./configs/inference/pose_videos/solo_pose.mp4: No such file or directory 这个意思是没有找到solo_pose.mp4这个文件吗？我是用的项目目录里面默认那个文件，是有的

**Comment by Zejun-Yang** [comment]
> ./configs/inference/pose_videos/solo_pose.mp4: No such file or directory 这个意思是没有找到solo_pose.mp4这个文件吗？我是用的项目目录里面默认那个文件，是有的

哦，没发现还有这个报错。可以检查一下您运行代码的路径是否在本项目的根目录下，即<your_root_path>/Aniportrait，因为该路径（./configs/inference/pose_videos/solo_pose.mp4）是相对路径。

**Comment by FLH1030** [comment]
运行路径是在根目录下的：(.conda) (base) hzq@inspur:/data/workpace/AniPortrait$ 
从报错的那个路径也是能直接点击打开视频的，现在output下面有生成一个视频文件，但是只有画面没有声音

**Comment by Zejun-Yang** [comment]
也有可能是ffmpeg安装异常。可以参考 #21 ，或者手动合成音频。
