### ISSUE TITLE
卡在0%一个小时

### ISSUE THREAD

**Issue by CodeABao** [Zejun-Yang/AniPortrait#79]
hi

我卡在如下界面一个小时了，就是慢还是因为BUG的存在，显卡3060 12GB。谢谢。

python -m scripts.audio2vid --config ./configs/prompts/animation_audio.yaml -W 512 -H 512

![image](https://github.com/Zejun-Yang/AniPortrait/assets/48180381/6af07243-19e3-49b4-bed4-34ad0ea8d2a8)

**config:**

pose_temp: "./configs/inference/head_pose_temp/yy_pose.npy"

test_cases:
  "./configs/inference/ref_images/yy.png":
    - "./configs/inference/audio/yy.wav"

**Comment by Zejun-Yang** [comment]
尝试设置 -L 30 检测是否代码是否运行正常。

**Comment by CodeABao** [comment]
> 尝试设置 -L 30 检测是否代码是否运行正常。

thanks, 可以了，我设置成- L 300运行成功
