### ISSUE TITLE
Program stucks when running inference scripts

### ISSUE THREAD

**Issue by AlexHex7** [Zejun-Yang/AniPortrait#8]
Hi~

    Environment: Python3.10, cuda11.8 and others follow requirements.txt
  
    IDE：VSCode Terminal, SSH to Ubuntu Server 
  
    Command: python -m scripts.vid2vid --config ./configs/prompts/animation_facereenac.yaml -W 512 -H 512 -L 64

Stucks in

    # AniPortrait/src/utils/face_landmark.py(line 3164)
    return cls( # <--
        task_info.generate_graph_config(
            enable_flow_limiting=options.running_mode
            == _RunningMode.LIVE_STREAM
        ),
        options.running_mode,
        packets_callback if options.result_callback else None,
    )
    
    # anaconda3/envs/ani/lib/python3.10/site-packages/mediapipe/tasks/python/vision/core/base_vision_task_api.py  (line 70)
    self._runner = _TaskRunner.create(graph_config, packet_callback) # <--

**Comment by Zejun-Yang** [comment]
The error looks not complete. And it is weird since we do not meet this bug before. Maybe you can check whether mediapipe==0.10.11. And make sure src/utils/mp_models/face_landmarker_v2_with_blendshapes.task is existed.

By the way, you can run our example for test. Copy the case in configs/prompts/animation_facereenac.yaml:
test_cases:
  "./configs/inference/ref_images/Aragaki.png":
    - "./configs/inference/video/Aragaki_song.mp4"

**Comment by AlexHex7** [comment]
@Zejun-Yang Thanks for replying.

The version of mediapipe is 0.10.11. 
I have not changed any code, yet.  The command is provided in ReadMe.md.

After the program stucks, I press Ctrl+C, then errors show out.

    I0000 00:00:1711607647.975712   27595 task_runner.cc:85] GPU suport is not available: INTERNAL: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:84) egl_initializedUnable to initialize EGL
    W0000 00:00:1711607647.976789   27595 face_landmarker_graph.cc:174] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
    
Maybe mediapipe installed by pip in this way is cpu version? Or GPU driver version of my server is not satisfied？(Driver Version: 515.105.01, check by nvidia-smi)
    # requirements.txt
    mediapipe==0.10.11

**Comment by FredWe** [comment]
same issue, inference may delegate to CPU, so process is slow,

here is my log:

```
/usr/local/lib/python3.10/dist-packages/diffusers/utils/outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
/usr/local/lib/python3.10/dist-packages/diffusers/utils/outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
2024-03-28 12:59:21.608636: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-03-28 12:59:21.608693: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-03-28 12:59:21.610025: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-03-28 12:59:22.772744: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/usr/local/lib/python3.10/dist-packages/diffusers/utils/outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
Some weights of Wav2Vec2Model were not initialized from the model checkpoint at ./pretrained_model/wav2vec2-base-960h and are newly initialized: ['wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original0', 'wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original1', 'wav2vec2.masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of the model checkpoint were not used when initializing UNet2DConditionModel: 
 ['conv_norm_out.weight, conv_norm_out.bias, conv_out.weight, conv_out.bias']
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1711630892.399963   26005 task_runner.cc:85] GPU suport is not available: INTERNAL: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:84) egl_initializedUnable to initialize EGL
W0000 00:00:1711630892.470891   26005 face_landmarker_graph.cc:174] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
I0000 00:00:1711630892.585868   26005 task_runner.cc:85] GPU suport is not available: INTERNAL: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:84) egl_initializedUnable to initialize EGL
pose video has 233 frames, with 30 fps
/content/AniPortrait/src/pipelines/pipeline_pose2vid_long.py:408: FutureWarning: Accessing config attribute `in_channels` directly via 'UNet3DConditionModel' object attribute is deprecated. Please access 'in_channels' over 'UNet3DConditionModel's config object instead, e.g. 'unet.config.in_channels'.
  num_channels_latents = self.denoising_unet.in_channels
 80% 20/25 [08:32<02:07, 25.53s/it]
```
