### ISSUE TITLE
Inference FPS of audio driven generation

### ISSUE THREAD

**Issue by mrtpk** [Zejun-Yang/AniPortrait#80]
Hi,

Thank you for sharing your work. Can you share an approximate FPS that you got while generating video driven by audio?

Thanks,
Thomas.

**Comment by FacePoluke** [comment]
The video generated by audio-driven method is at 30 FPS.  https://github.com/Zejun-Yang/AniPortrait/blob/e4601b8c023f0a9e46a4a6def2f524e9ded6cece/src/utils/audio_util.py#L20
