### ISSUE TITLE
After 40 minutes still stays on 0%

### ISSUE THREAD

**Issue by TomiTom1234** [Zejun-Yang/AniPortrait#83]
I installed everything perfectly. But when I run the command :
`python -m scripts.pose2vid --config ./configs/prompts/animation.yaml -W 512 -H 512`

the process stops here forever:
`E:\AI\AniPortrait\AniPortrait\src\pipelines\pipeline_pose2vid_long.py:408: FutureWarning: Accessing config attribute in_channels directly via 'UNet3DConditionModel' object attribute is deprecated. Please access 'in_channels' over 'UNet3DConditionModel's config object instead, e.g. 'unet.config.in_channels'. num_channels_latents = self.denoising_unet.in_channels 0%|                                                                                     | 0/25 [00:00<?, ?it/s]`

What is exactly the issue? What is messing?
My Gfx Card is RTX 3070 Ti 8 GB vRams.
Any help please?

![Screenshot 2024-04-02 233025](https://github.com/Zejun-Yang/AniPortrait/assets/125768071/6d9e7661-7844-453c-a798-45a6bcecd3f1)

**Comment by TomiTom1234** [comment]
Thank you for your reply.
I also added the -L 300 to the command line, the same result.
Actually, the video is the one that comes with the package by default (48 sec.)
What else may I check?

**Comment by TomiTom1234** [comment]
Thanks for the reply.

I added the -L 300 to the command line, and finally some improvements.
After around 30 minutes, it did 4%. 
Actually, the video is the sample that comes with the package (48 sec).
![Screenshot 2024-04-03 200302](https://github.com/Zejun-Yang/AniPortrait/assets/125768071/6a5c9f5d-968e-4d38-b138-639d4e5f718f)

Is there a way to increase the speed of the process? Or any tweaks here and there?

**Comment by Zejun-Yang** [comment]
https://huggingface.co/spaces/ZJYang/AniPortrait_official

We recommend you to use our gradio demo on hugging face.

**Comment by holycowdude** [comment]
the demo on hugging face doesn't seem to work?
I've been trying for two days but it just gives an error after a few hours

**Comment by Zejun-Yang** [comment]
> the demo on hugging face doesn't seem to work? I've been trying for two days but it just gives an error after a few hours

We have updated a new version with frame interpolation acceleration. You can have a try.
