### ISSUE TITLE
How to displace the 3d mesh?

### ISSUE THREAD

**Issue by harlanhong** [Zejun-Yang/AniPortrait#85]
How to draw this picture using the face_result['lmks3d']?
<img width="87" alt="image" src="https://github.com/Zejun-Yang/AniPortrait/assets/19970321/d650ba07-95e2-4a5b-ab2a-7c9856b56b6c">

**Comment by FacePoluke** [comment]
you can output face_result['lmks3d'] as obj file. Then you can use [meshlab](https://www.meshlab.net/) to visualize it.
