### ISSUE TITLE
vid2vid break will raise a exception

### ISSUE THREAD

**Issue by algorithmlover2016** [Zejun-Yang/AniPortrait#86]
video_length = min(len(src_tensor_list), len(pose_list))
for these codes in **scripts.vid2vid** in line 156 - 165:
```
for src_image_pil in source_images[: args_L: step]:
                src_tensor_list.append(pose_transform(src_image_pil))
                src_img_np = cv2.cvtColor(np.array(src_image_pil), cv2.COLOR_RGB2BGR)
                frame_height, frame_width, _ = src_img_np.shape
                src_img_result = lmk_extractor(src_img_np)
                if src_img_result is None:
                    break
                pose_trans_list.append(src_img_result['trans_mat'])
                verts_list.append(src_img_result['lmks3d'])
                bs_list.append(src_img_result['bs'])
```
if there is a break, it will lead to unequal between len(src_tensor_list) and len(pose_trans_list) by 1.
So maybe there are two ways to fix:
1:
`
  if src_img_result is None:
                    src_tensor_list.pop() # the last one
                    break
`
2: change` video_length = len(src_tensor_list)` to `video_length = min(len(src_tensor_list), len(pose_list))` and let it before `pose_list = np.array(pose_list)` in line 184

**Comment by Zejun-Yang** [comment]
Certainly, and we addressed this issue yesterday. You can update the code. Thank you for your suggestion!

https://github.com/Zejun-Yang/AniPortrait/commit/6d683ab4cf3750f1090a07b04dfcfae2fb9c7777
