### ISSUE TITLE
Speed up inference 

### ISSUE THREAD

**Issue by MahdiMohseni0033** [Zejun-Yang/AniPortrait#89]
Thanks for your amazing work. I had question regarding the network.
is it possible to replace the SD1.5 with a faster counterpart like SDXL-Turbo which generate good images in fewer time, in order to increase the speed? 
I mostly meant, does your networked trained based on the SD1.5 or it is replaceable without further fine-tuning?

**Comment by Zejun-Yang** [comment]
Undoubtedly, substituting a faster backbone can accelerate the inference process. However, it is essential to retrain the new model using the training dataset, as a direct replacement will not suffice.
