### ISSUE TITLE
about train

### ISSUE THREAD

**Issue by onedotone-wei** [Zejun-Yang/AniPortrait#90]
thanks.
according to readme, a json file is generated, and when train_stage_1.py is run, len(train_dataloader) results in 0, cfg.solver.max_train_steps/num_update_steps_per_epoch this will cause an error. 
try to set num_update_steps_per_epoch to 1, enumerate(train_dataloader) displays TypeError: 'NoneType' object is not subscriptable
what is the reason?

**Comment by onedotone-wei** [comment]
I think I understand

**Comment by Mxwgreat** [comment]
Hi, I also encountered the same problem as you. Have you solved the problem? If so, could you tell me how to solve it? Thanks

**Comment by Mxwgreat** [comment]
@onedotone-wei  Hi, I also encountered the same problem as you. Have you solved your problem? If so, could you tell me how to solve it?
