### ISSUE TITLE
关于audio2landmark

### ISSUE THREAD

**Issue by zouwuhe** [Zejun-Yang/AniPortrait#95]
很棒的工作，非常感谢分享
我有几个疑问想确认一下
1. self-driven其实是从视频生成posevideo或者已有posevideo的情况结合静态image生成新的video，对吗
2. Face reenacment 其实是把self-driven的两个step合并到一起了 从视频1生成pose，再结合pose和静态image生成视频2，对吗
3. audio-driven 是pose + image + audio 生成video 对吗
- 这部分是我最困惑的，按论文是不是应该基于audio生成posevideo —— audio2landmark
- 从audio到posevideo这一步 就是todo list里面的audio2pose pre-trained weight 对吗
- 看论文说明 这个audio2landmark似乎包括audio2mesh（单人1小时高质量音频训练）和audio2pose（HDTF数据训练）两部分对吗
- 那每个人的audio2landmark应该不一样（不同人说同一段音频表情神态/口型幅度不同）所以audio2lankmark是否可以支持针对特定一个人的数据进行微调？
期待您的解答

**Comment by FacePoluke** [comment]
self-driven和face reenacment都是我们衍生的使用方式。
audio2lmk支持微调，你可以收集某个人的数据来重新训audio2lmk模型。数据获取脚本是[preprocess_dataset.py](https://github.com/Zejun-Yang/AniPortrait/blob/main/scripts/preprocess_dataset.py) 或者借鉴[FaceFormer](https://github.com/EvelynFan/FaceFormer)的方式，一个模型支持多个ID。

**Comment by zouwuhe** [comment]
太棒了 感谢回复
