### ISSUE TITLE
accelerate config？

### ISSUE THREAD

**Issue by 1595813520** [Zejun-Yang/AniPortrait#97]
能否看看作者的accelerate config？我想参考一下deepspeed等配置，如下图
​​​​
![image](https://github.com/Zejun-Yang/AniPortrait/assets/152386277/5ac47009-00a9-4951-bf99-bb5fd2d80bbf)

我用四张3090训练第一阶段，OOM了

**Comment by 1595813520** [comment]
我的accelerate配置：
![image](https://github.com/Zejun-Yang/AniPortrait/assets/152386277/cb8b4b14-3b27-42b2-8249-a6ab51afd8cb)
开始训练时报如下错：
![image](https://github.com/Zejun-Yang/AniPortrait/assets/152386277/a0a8951a-9746-4dfb-868b-6ae9c2835f25)
![image](https://github.com/Zejun-Yang/AniPortrait/assets/152386277/0fdbd266-01e9-4356-8b35-73ee2f34746d)

没有修改模型，qingw请问该如何解决呢？
期待回复！

**Comment by Zejun-Yang** [comment]
我们是在四张A100上训练的，单张3090应该无法承载第二阶段的训练。另外上图报错数据类型不一致，可能是不支持半精度训练导致的。

**Comment by 1595813520** [comment]
> 我们是在四张A100上训练的，3090应该无法承载第二阶段的训练。另外上图报错数据类型不一致，可能是不支持半精度训练导致的。

作者您好，感谢您的回复！该数据类型不一致的报错发生在第一阶段训练，我的硬件和框架应该都是支持半精度训练的，请问是否有别的原因导致该报错呢？期待您的回复，非常感谢！
![image](https://github.com/Zejun-Yang/AniPortrait/assets/152386277/33b1cf24-20bb-4e04-a070-122f600d5b36)

**Comment by 1595813520** [comment]
这是我的accelerate config：
![image](https://github.com/Zejun-Yang/AniPortrait/assets/152386277/fc5bd197-451f-4a46-b054-dd125f90f4b2)
是否该启用torch dynamo或deepspeed呢？
