### ISSUE TITLE
Request: Add the ability to use base models like SDXL and output 1024x1024

### ISSUE THREAD

**Issue by gessyoo** [Zejun-Yang/AniPortrait#98]

**Comment by gessyoo** [comment]
I don't know whether adding SDXL will break the existing pipeline, but I'd like to try it if it's feasible.

**Comment by Zejun-Yang** [comment]
We have finetuned the weight of SD1.5 in AniPortrait. Therefore, directly replacing it with SDXL without retraining will result in poor performance. So you need to finetune SDXL on training dataset either.
