### ISSUE TITLE
img = cv2.imread(img_file)[:600, 650:1350]

### ISSUE THREAD

**Issue by bronzeman2022** [Zejun-Yang/AniPortrait#99]
![image](https://github.com/Zejun-Yang/AniPortrait/assets/115131035/8752eb0a-f19a-4403-b788-2b0834d9edca)
大佬 这里是处理图片的时候是想要截取图片的上半部分吗？img = cv2.imread(img_file)[:600, 650:1350]好像也不是这个意思。

**Comment by Zejun-Yang** [comment]
这是我们处理自建数据集的临时参数，可以删除该切片index。
也可以直接更新代码，当前版本我们已修复这一问题。
